name: Pull Request Checks

on: [pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check correct commit formatting
        uses: wagoid/commitlint-github-action@v4
        env:
          NODE_PATH: ${{ github.workspace }}/node_modules

      - name: Check formatting
        run: yarn prettier-check

      - name: Build Plugin
        run: yarn prod
